// Fetches every work's running time from TMDB and rewrites
// `src/data/runtimes.ts`. Needs a TMDB API read access token, from the
// environment or `.env.local` (TMDB_TOKEN=...): pnpm fetch:runtimes
import { writeFileSync } from "node:fs";

import { WORKS } from "../src/data/works.ts";
import { tmdbPath } from "../src/lib/tmdb-diff.ts";
import { runtimeOf, type Runtime, type TmdbRuntimeDetails } from "../src/lib/tmdb-runtime.ts";

const token = process.env.TMDB_TOKEN;
if (!token) {
  console.error("Set TMDB_TOKEN to a TMDB API read access token (themoviedb.org/settings/api).");
  process.exit(2);
}

async function fetchDetails(path: string): Promise<TmdbRuntimeDetails | null> {
  const response = await fetch(`https://api.themoviedb.org/3${path}`, {
    headers: { Authorization: `Bearer ${token}`, Accept: "application/json" },
  });
  if (response.status === 404) return null;
  if (!response.ok) throw new Error(`${path}: HTTP ${response.status}`);
  return (await response.json()) as TmdbRuntimeDetails;
}

const runtimes = new Map<string, Runtime>();
const failures: string[] = [];
// A few at a time, well under TMDB's rate limit.
const BATCH = 8;
for (let i = 0; i < WORKS.length; i += BATCH) {
  await Promise.all(
    WORKS.slice(i, i + BATCH).map(async (work) => {
      try {
        const details = await fetchDetails(tmdbPath(work));
        const runtime = details && runtimeOf(work, details);
        if (runtime) runtimes.set(work.id, runtime);
      } catch (error) {
        failures.push(`${work.id}: ${(error as Error).message}`);
      }
    }),
  );
}
if (failures.length > 0) {
  for (const failure of failures) console.error(`failed  ${failure}`);
  process.exit(1);
}

// In the works' own order, so diffs stay readable.
const entries = WORKS.filter((w) => runtimes.has(w.id)).map((w) => {
  const { minutes, episodes } = runtimes.get(w.id)!;
  const fields = episodes ? `minutes: ${minutes}, episodes: ${episodes}` : `minutes: ${minutes}`;
  return `  "${w.id}": { ${fields} },`;
});
writeFileSync(
  new URL("../src/data/runtimes.ts", import.meta.url),
  `// Generated by \`pnpm fetch:runtimes\` from TMDB; don't edit by hand. Works
// TMDB has no complete runtime for yet are left out.
import type { Runtime } from "../lib/tmdb-runtime.ts";

export const RUNTIMES: Record<string, Runtime> = {
${entries.join("\n")}
};
`,
);
console.log(`${runtimes.size} of ${WORKS.length} works have a runtime`);
