// Generated by `pnpm fetch:runtimes` from TMDB; don't edit by hand. Works
// TMDB has no complete runtime for yet are left out.
import type { Runtime } from "../lib/tmdb-runtime.ts";

export const RUNTIMES: Record<string, Runtime> = {};
